version: '3.9'
services:
  front:
    container_name: cartrader_front
    platform: linux/amd64
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./front:/workspace
